name: Analyse TFDefectGA

on:
  push:
    paths:
      - '**.tf'
  workflow_dispatch: {}

jobs:
  tfdefect-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: TFDefectGA
        uses: TFDefect/TFDefectGA@v1.0.0
        with:
          model: randomforest
